apiVersion: v1
kind: ConfigMap
metadata:
  name: cassino-build
  labels:
    app: cassino-build
data:
  build.sh: |
    #!/bin/sh

    if [ ! -e /dev/cassino* ] ; then
      sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
      sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*

      export KERNEL=$(basename /usr/src/kernels/${1}*)
      export KERNELDIR=/lib/modules/$KERNEL/build
      mkdir -p /lib/modules/$KERNEL
      ln -s /usr/src/kernels/$KERNEL /lib/modules/$KERNEL/build;

      yum install -y kernel-devel git make gcc elfutils-libelf-devel kmod
      git clone https://github.com/cassino/linux-cassino-backport.git
      cd linux-cassino-backport
      git checkout n5010/fpga-ofs-dev-5.15-lts
      make
      make install
      make insmod
    fi

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cassino-daemonset
  labels:
    app: cassino
spec:
  selector:
    matchLabels:
      app: cassino
  template:
    metadata:
      labels:
        app: cassino
    spec:
      nodeSelector:
        fpga.silicom.dk/cassino: "true"
      initContainers:
      - name: cassino-build
        image: docker.io/centos:8.4.2105
        command: ["/bin/bash"]
        args: ["-c", "/data/build.sh"]
      containers:
      - name: cassino
        image: quay.io/silicom/cassino-runtime:2.1.0-1
        command: ["/bin/bash"]
        args: ["-c", "while true ; do ; fpgainfo bmc; sleep 30; done"]
      volumeMounts:
      - name: devfs
        mountPath: /dev
      - name: cassino-build
        mountPath: /data
      securityContext:
        privileged: true
      resources:
        limits:
          memory: 200Mi
        requests:
          cpu: 100m
          memory: 200Mi
    volumes:
      - name:  devfs
        hostPath:
          path: /dev
      - name: cassino-build
        configMap:
          name:  cassino-build

